// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Gat.Event.Xml {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gatcdc.org/schema/project/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.gatcdc.org/schema/project/1.0", IsNullable=false)]
    public partial class gatEvent {
        
        private string idField;
        
        private gatEventType typeField;
        
        private string catalogField;
        
        private string schemaField;
        
        private string tableField;
        
        private string sqlField;
        
        private gatRowSet rowSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public gatEventType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string schema {
            get {
                return this.schemaField;
            }
            set {
                this.schemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string sql {
            get {
                return this.sqlField;
            }
            set {
                this.sqlField = value;
            }
        }
        
        /// <remarks/>
        public gatRowSet rowSet {
            get {
                return this.rowSetField;
            }
            set {
                this.rowSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gatcdc.org/schema/project/1.0")]
    public enum gatEventType {
        
        /// <remarks/>
        INSERT,
        
        /// <remarks/>
        UPDATE,
        
        /// <remarks/>
        DELETE,
        
        /// <remarks/>
        CREATE,
        
        /// <remarks/>
        ALTER,
        
        /// <remarks/>
        DROP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gatcdc.org/schema/project/1.0")]
    public partial class gatRowSet {
        
        private gatColumn[] columnField;
        
        private gatValue[][] rowField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("column")]
        public gatColumn[] column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("row")]
        public gatValue[][] row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gatcdc.org/schema/project/1.0")]
    public partial class gatColumn {
        
        private int ordinalField;
        
        private string nameField;
        
        private gatColumnType typeField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int ordinal {
            get {
                return this.ordinalField;
            }
            set {
                this.ordinalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public gatColumnType type {
            get {
                return this.typeField1;
            }
            set {
                this.typeField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gatcdc.org/schema/project/1.0")]
    public partial class gatColumnType {
        
        private gatDataType typeField2;
        
        private string typeNameField;
        
        private int precisionField;
        
        private bool precisionSpecifiedField;
        
        private int scaleField;
        
        private bool scaleSpecifiedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public gatDataType type {
            get {
                return this.typeField2;
            }
            set {
                this.typeField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string typeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int precision {
            get {
                return this.precisionField;
            }
            set {
                this.precisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool precisionSpecified {
            get {
                return this.precisionSpecifiedField;
            }
            set {
                this.precisionSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool scaleSpecified {
            get {
                return this.scaleSpecifiedField;
            }
            set {
                this.scaleSpecifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gatcdc.org/schema/project/1.0")]
    public enum gatDataType {
        
        /// <remarks/>
        ARRAY,
        
        /// <remarks/>
        BIGINT,
        
        /// <remarks/>
        BINARY,
        
        /// <remarks/>
        BIT,
        
        /// <remarks/>
        BLOB,
        
        /// <remarks/>
        BOOLEAN,
        
        /// <remarks/>
        CHAR,
        
        /// <remarks/>
        CLOB,
        
        /// <remarks/>
        DATALINK,
        
        /// <remarks/>
        DATE,
        
        /// <remarks/>
        DECIMAL,
        
        /// <remarks/>
        DISTINCT,
        
        /// <remarks/>
        DOUBLE,
        
        /// <remarks/>
        FLOAT,
        
        /// <remarks/>
        INTEGER,
        
        /// <remarks/>
        LONGNVARCHAR,
        
        /// <remarks/>
        LONGVARBINARY,
        
        /// <remarks/>
        LONGVARCHAR,
        
        /// <remarks/>
        NCHAR,
        
        /// <remarks/>
        NCLOB,
        
        /// <remarks/>
        NULL,
        
        /// <remarks/>
        NUMERIC,
        
        /// <remarks/>
        NVARCHAR,
        
        /// <remarks/>
        OTHER,
        
        /// <remarks/>
        REAL,
        
        /// <remarks/>
        REF,
        
        /// <remarks/>
        ROWID,
        
        /// <remarks/>
        SMALLINT,
        
        /// <remarks/>
        SQLXML,
        
        /// <remarks/>
        STRUCT,
        
        /// <remarks/>
        TIME,
        
        /// <remarks/>
        TIMESTAMP,
        
        /// <remarks/>
        TINYINT,
        
        /// <remarks/>
        VARBINARY,
        
        /// <remarks/>
        VARCHAR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gatcdc.org/schema/project/1.0")]
    public partial class gatValue {
        
        private int ordinalField1;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int ordinal {
            get {
                return this.ordinalField1;
            }
            set {
                this.ordinalField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public byte[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gatcdc.org/schema/project/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.gatcdc.org/schema/project/1.0", IsNullable=false)]
    public partial class gatEventResponse {
        
        private bool rollbackField;
        
        private bool rollbackSpecifiedField;
        
        private string executeInsteadField;
        
        private gatRowSet returnInsteadField;
        
        private string[] messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public bool rollback {
            get {
                return this.rollbackField;
            }
            set {
                this.rollbackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool rollbackSpecified {
            get {
                return this.rollbackSpecifiedField;
            }
            set {
                this.rollbackSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string executeInstead {
            get {
                return this.executeInsteadField;
            }
            set {
                this.executeInsteadField = value;
            }
        }
        
        /// <remarks/>
        public gatRowSet returnInstead {
            get {
                return this.returnInsteadField;
            }
            set {
                this.returnInsteadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message")]
        public string[] message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
}
