/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace Gat.Event.Thrift
{
  public enum GatDataType
  {
    ARRAY = 0,
    BIGINT = 1,
    BINARY = 2,
    BIT = 3,
    BLOB = 4,
    BOOLEAN = 5,
    CHAR = 6,
    CLOB = 7,
    DATALINK = 8,
    DATE = 9,
    DECIMAL = 10,
    DISTINCT = 11,
    DOUBLE = 12,
    FLOAT = 13,
    INTEGER = 14,
    LONGNVARCHAR = 15,
    LONGVARBINARY = 16,
    LONGVARCHAR = 17,
    NCHAR = 18,
    NCLOB = 19,
    NULL = 20,
    NUMERIC = 21,
    NVARCHAR = 22,
    OTHER = 23,
    REAL = 24,
    REF = 25,
    ROWID = 26,
    SMALLINT = 27,
    SQLXML = 28,
    STRUCT = 29,
    TIME = 30,
    TIMESTAMP = 31,
    TINYINT = 32,
    VARBINARY = 33,
    VARCHAR = 34,
  }
}
