/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace Gat.Event.Thrift
{
  public enum GatEventType
  {
    INSERT = 0,
    UPDATE = 1,
    DELETE = 2,
    CREATE = 3,
    ALTER = 4,
    DROP = 5,
  }
}
