//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: proto-rpc enabled
  
// Generated from: format/gat-event.proto
namespace Gat.Event.Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GatColumnType")]
  public partial class GatColumnType : global::ProtoBuf.IExtensible
  {
    public GatColumnType() {}
    
    private GatDataType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GatDataType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _typeName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"typeName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string typeName
    {
      get { return _typeName; }
      set { _typeName = value; }
    }

    private int _precision = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"precision", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int precision
    {
      get { return _precision; }
      set { _precision = value; }
    }

    private int _scale = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GatColumn")]
  public partial class GatColumn : global::ProtoBuf.IExtensible
  {
    public GatColumn() {}
    
    private int _ordinal;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ordinal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ordinal
    {
      get { return _ordinal; }
      set { _ordinal = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private GatColumnType _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public GatColumnType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GatValue")]
  public partial class GatValue : global::ProtoBuf.IExtensible
  {
    public GatValue() {}
    
    private int _ordinal;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ordinal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ordinal
    {
      get { return _ordinal; }
      set { _ordinal = value; }
    }

    private byte[] _value = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GatRow")]
  public partial class GatRow : global::ProtoBuf.IExtensible
  {
    public GatRow() {}
    
    private readonly global::System.Collections.Generic.List<GatValue> _values = new global::System.Collections.Generic.List<GatValue>();
    [global::ProtoBuf.ProtoMember(1, Name=@"values", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GatValue> values
    {
      get { return _values; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GatRowSet")]
  public partial class GatRowSet : global::ProtoBuf.IExtensible
  {
    public GatRowSet() {}
    
    private readonly global::System.Collections.Generic.List<GatColumn> _columns = new global::System.Collections.Generic.List<GatColumn>();
    [global::ProtoBuf.ProtoMember(1, Name=@"columns", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GatColumn> columns
    {
      get { return _columns; }
    }
  
    private readonly global::System.Collections.Generic.List<GatRow> _rows = new global::System.Collections.Generic.List<GatRow>();
    [global::ProtoBuf.ProtoMember(2, Name=@"rows", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GatRow> rows
    {
      get { return _rows; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GatEvent")]
  public partial class GatEvent : global::ProtoBuf.IExtensible
  {
    public GatEvent() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private GatEventType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GatEventType type
    {
      get { return _type; }
      set { _type = value; }
    }

    private string _catalog = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"catalog", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string catalog
    {
      get { return _catalog; }
      set { _catalog = value; }
    }

    private string _schema = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"schema", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string schema
    {
      get { return _schema; }
      set { _schema = value; }
    }

    private string _table = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"table", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string table
    {
      get { return _table; }
      set { _table = value; }
    }

    private string _sql = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sql", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sql
    {
      get { return _sql; }
      set { _sql = value; }
    }

    private GatRowSet _rowSet = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"rowSet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public GatRowSet rowSet
    {
      get { return _rowSet; }
      set { _rowSet = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GatEventResponse")]
  public partial class GatEventResponse : global::ProtoBuf.IExtensible
  {
    public GatEventResponse() {}
    

    private bool _rollback = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rollback", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool rollback
    {
      get { return _rollback; }
      set { _rollback = value; }
    }

    private string _executeInstead = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"executeInstead", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string executeInstead
    {
      get { return _executeInstead; }
      set { _executeInstead = value; }
    }

    private GatRowSet _returnInstead = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"returnInstead", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public GatRowSet returnInstead
    {
      get { return _returnInstead; }
      set { _returnInstead = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _messages = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"messages", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> messages
    {
      get { return _messages; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GatEventType")]
    public enum GatEventType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"INSERT", Value=0)]
      INSERT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE", Value=1)]
      UPDATE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DELETE", Value=2)]
      DELETE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE", Value=3)]
      CREATE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALTER", Value=4)]
      ALTER = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DROP", Value=5)]
      DROP = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GatDataType")]
    public enum GatDataType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARRAY", Value=0)]
      ARRAY = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BIGINT", Value=1)]
      BIGINT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BINARY", Value=2)]
      BINARY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BIT", Value=3)]
      BIT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLOB", Value=4)]
      BLOB = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BOOLEAN", Value=5)]
      BOOLEAN = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAR", Value=6)]
      CHAR = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLOB", Value=7)]
      CLOB = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DATALINK", Value=8)]
      DATALINK = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DATE", Value=9)]
      DATE = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DECIMAL", Value=10)]
      DECIMAL = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DISTINCT", Value=11)]
      DISTINCT = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DOUBLE", Value=12)]
      DOUBLE = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FLOAT", Value=13)]
      FLOAT = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INTEGER", Value=14)]
      INTEGER = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LONGNVARCHAR", Value=15)]
      LONGNVARCHAR = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LONGVARBINARY", Value=16)]
      LONGVARBINARY = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LONGVARCHAR", Value=17)]
      LONGVARCHAR = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NCHAR", Value=18)]
      NCHAR = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NCLOB", Value=19)]
      NCLOB = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NULL", Value=20)]
      NULL = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NUMERIC", Value=21)]
      NUMERIC = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NVARCHAR", Value=22)]
      NVARCHAR = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER", Value=23)]
      OTHER = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REAL", Value=24)]
      REAL = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REF", Value=25)]
      REF = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROWID", Value=26)]
      ROWID = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SMALLINT", Value=27)]
      SMALLINT = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SQLXML", Value=28)]
      SQLXML = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STRUCT", Value=29)]
      STRUCT = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TIME", Value=30)]
      TIME = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TIMESTAMP", Value=31)]
      TIMESTAMP = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TINYINT", Value=32)]
      TINYINT = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VARBINARY", Value=33)]
      VARBINARY = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VARCHAR", Value=34)]
      VARCHAR = 34
    }
  
    public interface IGatConsumer
    {
      GatEventResponse onEvent(GatEvent request);
    
    }
    
    
    public class GatConsumerClient : global::ProtoBuf.ServiceModel.RpcClient
    {
      public GatConsumerClient() : base(typeof(IGatConsumer)) { }
      GatEventResponse onEvent(GatEvent request)
        {
            return (GatEventResponse) Send(@"onEvent", request);
        }
  
    }
    
}